apiVersion: v1
kind: ConfigMap
metadata:
  name: common-feature-flags
  namespace: qa
data:
  FEATURE_FLAG_SQL: "true"
  FEATURE_FLAG_ADMIN_CLIENT: "true"
  FEATURE_FLAG_SIGNALHUB_WHITELIST: "false"
  FEATURE_FLAG_AGREEMENT_APPROVAL_POLICY_UPDATE: "true"
  FEATURE_FLAG_CLIENT_ASSERTION_STRICT_CLAIMS_VALIDATION: "true"
  FEATURE_FLAG_IMPROVED_PRODUCER_VERIFICATION_CLAIMS: "true"
  FEATURE_FLAG_NOTIFICATION_CONFIG: "false"
  FEATURE_FLAG_PURPOSE_TEMPLATE: "false"
  FEATURE_FLAG_ESERVICE_PERSONAL_DATA: "true"
  SIGNALHUB_WHITELIST_CONSUMER: "496ffce2-021f-4541-bad4-7a3b88f678de"
  SIGNALHUB_WHITELIST_PRODUCER: "e8b418e3-0972-4b55-8bda-609a817073ee"
