name: "interop-be-certified-email-sender"
techStack: "nodejs"

service:
  create: true
  containerPort: 8088

serviceAccount:
  roleArn: "arn:aws:iam::533267098416:role/interop-be-certified-email-sender-att-es1"

configmap:
  KAFKA_CLIENT_ID: "{{.Values.namespace}}-pagopa-interop-certified-email-sender"
  KAFKA_GROUP_ID: "{{.Values.namespace}}-certified-email-sender"
  PEC_SMTP_ADDRESS: "smtp-mock.{{.Values.namespace}}.svc.cluster.local"
  PEC_SMTP_PORT: "5025"
  PEC_SMTP_SECURE: "false"
  INTEROP_FE_BASE_URL: "selfcare.{{.Values.namespace}}.interop.pagopa.it"

deployment:
  env:
    TOPIC_STARTING_OFFSET: "latest"
  envFromFieldRef:
    AWS_ROLE_SESSION_NAME: "metadata.name"
    NAMESPACE: "metadata.namespace"
  envFromConfigmaps:
    AGREEMENT_TOPIC: "common-kafka.AGREEMENT_TOPIC"
    KAFKA_BROKERS: "common-kafka.KAFKA_BROKERS"
    READMODEL_DB_HOST: "common-read-model.READMODEL_DB_HOST"
    READMODEL_DB_NAME: "common-read-model.READMODEL_DB_NAME"
    READMODEL_DB_PORT: "common-read-model.READMODEL_DB_PORT"
    READMODEL_DB_REPLICA_SET: "common-read-model.READMODEL_REPLICA_SET"
    READMODEL_DB_READ_PREFERENCE: "common-read-model.READMODEL_READ_PREFERENCE"
    READMODEL_SQL_DB_HOST: "common-read-model-sql.DB_HOST_RO"
    READMODEL_SQL_DB_PORT: "common-read-model-sql.DB_PORT"
    READMODEL_SQL_DB_NAME: "common-read-model-sql.DB_NAME"
    READMODEL_SQL_DB_USE_SSL: "common-read-model-sql.DB_USE_SSL"
    READMODEL_SQL_DB_SCHEMA_AGREEMENT: "common-read-model-sql.DB_SCHEMA_AGREEMENT"
    READMODEL_SQL_DB_SCHEMA_ATTRIBUTE: "common-read-model-sql.DB_SCHEMA_ATTRIBUTE"
    READMODEL_SQL_DB_SCHEMA_CATALOG: "common-read-model-sql.DB_SCHEMA_CATALOG"
    READMODEL_SQL_DB_SCHEMA_CLIENT_JWK_KEY: "common-read-model-sql.DB_SCHEMA_CLIENT_JWK_KEY"
    READMODEL_SQL_DB_SCHEMA_CLIENT: "common-read-model-sql.DB_SCHEMA_CLIENT"
    READMODEL_SQL_DB_SCHEMA_DELEGATION: "common-read-model-sql.DB_SCHEMA_DELEGATION"
    READMODEL_SQL_DB_SCHEMA_ESERVICE_TEMPLATE: "common-read-model-sql.DB_SCHEMA_ESERVICE_TEMPLATE"
    READMODEL_SQL_DB_SCHEMA_NOTIFICATION_CONFIG: "common-read-model-sql.DB_SCHEMA_NOTIFICATION_CONFIG"
    READMODEL_SQL_DB_SCHEMA_PRODUCER_JWK_KEY: "common-read-model-sql.DB_SCHEMA_PRODUCER_JWK_KEY"
    READMODEL_SQL_DB_SCHEMA_PRODUCER_KEYCHAIN: "common-read-model-sql.DB_SCHEMA_PRODUCER_KEYCHAIN"
    READMODEL_SQL_DB_SCHEMA_PURPOSE: "common-read-model-sql.DB_SCHEMA_PURPOSE"
    READMODEL_SQL_DB_SCHEMA_TENANT: "common-read-model-sql.DB_SCHEMA_TENANT"
    FEATURE_FLAG_SQL: "common-feature-flags.FEATURE_FLAG_SQL"
  envFromSecrets:
    PEC_SENDER_MAIL: "smtp-certified.PEC_SMTP_SENDER"
    PEC_SENDER_LABEL: "smtp-certified.PEC_SMTP_SENDER"
    PEC_SMTP_USERNAME: "smtp-certified.PEC_SMTP_USER"
    PEC_SMTP_PASSWORD: "smtp-certified.PEC_SMTP_PASSWORD"
    READMODEL_DB_USERNAME: "read-model.READONLY_USR"
    READMODEL_DB_PASSWORD: "read-model.READONLY_PSW"
    READMODEL_SQL_DB_USERNAME: "platform-data-certified-email-sender-user.username"
    READMODEL_SQL_DB_PASSWORD: "platform-data-certified-email-sender-user.password"
