apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: interop-microservices-appset
  labels:
    app.kubernetes.io/part-of: interop-appset-microservices
    argocd.argoproj.io/instance: interop-ms-appset
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
  - matrix:
      generators:
      - list:
          elements:
          - env: dev-experimental-argocd-interop-apps
            namespace: dev-experimental-argocd-interop-apps
            project: default
      - git:
          repoURL: https://github.com/pagopa/interop-core-deployment.git
          revision: feature/argocd
          pathParamPrefix: ms
          directories:
          - path: microservices/*
  template:
    metadata:
      name: '{{.ms.path.basename}}'
      namespace: dev-experimental-argocd-interop-apps
      labels:
        appset: interop-microservices-appset
        app.kubernetes.io/part-of: interop-appset-microservices
        env: '{{.env}}'
      service: '{{.ms.path.basename}}'
    spec:
      project: '{{project}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: dev-experimental-argocd-interop-apps
      source:
        repoURL: https://github.com/pagopa/interop-core-deployment.git
        targetRevision: feature/argocd
        path: '.'
        plugin:
          name: infra-commons-microservices-plugin
          env:
          - name: ENV
            value: '{{.env}}'
          - name: SERVICE
            value: '{{.ms.path.basename}}'
          - name: IMAGES_FILE
            value: "commons/{{.env}}/images.yaml"
          - name: PROJECT_DIR
            value: "."
