apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: interop-app-root-post-sync-hook
  namespace: dev-experimental-argocd-interop-apps
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-experimental-argocd-interop-apps
  sources:
  - repoURL: https://github.com/pagopa/interop-core-deployment.git
    targetRevision: feature/argocd
    path: argocd/dev-experimental-argocd-interop-post-sync-hook
    directory:
      include: 'common-cm.yaml'
  - repoURL: https://github.com/pagopa/interop-core-deployment.git
    targetRevision: feature/argocd
    path: argocd/dev-experimental-argocd-interop-post-sync-hook
    directory:
      include: 'microservices-appset.yaml'
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
