name: "interop-be-selfcare-onboarding-consumer"
techStack: "nodejs"

serviceAccount:
  roleArn: "arn:aws:iam::697818730278:role/interop-be-selfcare-onboarding-consumer-prod-es1"

service:
  create: true
  
configmap:
  KAFKA_BROKERS: "selc-p-eventhub-ns.servicebus.windows.net:9093"
  KAFKA_CLIENT_ID: "interop-prod"
  KAFKA_GROUP_ID: "interop-onboarding-prod"
  SELFCARE_TOPIC: "sc-contracts"
  RESET_CONSUMER_OFFSETS: "FALSE"
  INTEROP_PRODUCT: "prod-interop"
  ALLOWED_ORIGINS: "IPA,ANAC,IVASS,PDND_INFOCAMERE-SCP"
  INTERNAL_JWT_KID: "{{.Values.local.interop_be_commons.RSA_KEYS_IDENTIFIERS}}"
  INTERNAL_JWT_SUBJECT: "interop-m2m"
  INTERNAL_JWT_ISSUER: "interop.pagopa.it"
  INTERNAL_JWT_AUDIENCE: "interop.pagopa.it/internal"
  INTERNAL_JWT_SECONDS_DURATION: "3600"

deployment:
  envFromFieldRef:
    NAMESPACE: "metadata.namespace"
  envFromConfigmaps:
    TENANT_PROCESS_URL: "common-services-urls.TENANT_PROCESS_URL"
  envFromSecrets:
    KAFKA_BROKER_CONNECTION_STRING: "selfcare-v2.SELFCARE_BROKER_CONNECTION_STRING"
