apiVersion: v1
kind: ConfigMap
metadata:
  name: common-scheduled-notification-db
  namespace: att
data:
  DB_HOST_RW: "interop-platform-data-att.cluster-c5mm6mwy4v3q.eu-south-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "scheduled_notification"
  DB_USE_SSL: "true"
  DB_SCHEMA: "att_scheduled_notification"
