name: "interop-be-eservice-descriptors-scheduled-archiver"

serviceAccount:
  roleArn: "arn:aws:iam::{{.Values.local.awsAccountId}}:role/interop-be-eservice-descriptors-scheduled-archiver-{{.Values.namespace}}-es1"

configmap:
  INTERNAL_JWT_KID: "{{.Values.local.interop_be_commons.RSA_KEYS_IDENTIFIERS}}"
  INTERNAL_JWT_SUBJECT: "{{.Values.namespace}}.interop-eservice-descriptors-scheduled-archiver"
  INTERNAL_JWT_ISSUER: "{{.Values.namespace}}.interop.pagopa.it"
  INTERNAL_JWT_AUDIENCE: "{{.Values.namespace}}.interop.pagopa.it/internal"
  INTERNAL_JWT_SECONDS_DURATION: "1800"
  CATALOG_API_CONCURRENCY: "5"
  DEFAULT_POLLING_RETRY_DELAY: "300"
  DEFAULT_POLLING_MAX_RETRIES: "20"

cronjob:
  schedule: "30 6 * * 1-5"
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  restartPolicy: Never
  concurrencyPolicy: Forbid
  automountServiceAccountToken: false

  envFromConfigmaps:
    CATALOG_PROCESS_URL: "common-services-urls.CATALOG_PROCESS_URL"
    READMODEL_SQL_DB_HOST: "common-read-model-sql.DB_HOST_RO"
    READMODEL_SQL_DB_PORT: "common-read-model-sql.DB_PORT"
    READMODEL_SQL_DB_NAME: "common-read-model-sql.DB_NAME"
    READMODEL_SQL_DB_USE_SSL: "common-read-model-sql.DB_USE_SSL"
    READMODEL_SQL_DB_SCHEMA_AGREEMENT: "common-read-model-sql.DB_SCHEMA_AGREEMENT"
    READMODEL_SQL_DB_SCHEMA_ATTRIBUTE: "common-read-model-sql.DB_SCHEMA_ATTRIBUTE"
    READMODEL_SQL_DB_SCHEMA_CATALOG: "common-read-model-sql.DB_SCHEMA_CATALOG"
    READMODEL_SQL_DB_SCHEMA_CLIENT_JWK_KEY: "common-read-model-sql.DB_SCHEMA_CLIENT_JWK_KEY"
    READMODEL_SQL_DB_SCHEMA_CLIENT: "common-read-model-sql.DB_SCHEMA_CLIENT"
    READMODEL_SQL_DB_SCHEMA_DELEGATION: "common-read-model-sql.DB_SCHEMA_DELEGATION"
    READMODEL_SQL_DB_SCHEMA_ESERVICE_TEMPLATE: "common-read-model-sql.DB_SCHEMA_ESERVICE_TEMPLATE"
    READMODEL_SQL_DB_SCHEMA_NOTIFICATION_CONFIG: "common-read-model-sql.DB_SCHEMA_NOTIFICATION_CONFIG"
    READMODEL_SQL_DB_SCHEMA_PRODUCER_JWK_KEY: "common-read-model-sql.DB_SCHEMA_PRODUCER_JWK_KEY"
    READMODEL_SQL_DB_SCHEMA_PRODUCER_KEYCHAIN: "common-read-model-sql.DB_SCHEMA_PRODUCER_KEYCHAIN"
    READMODEL_SQL_DB_SCHEMA_PURPOSE: "common-read-model-sql.DB_SCHEMA_PURPOSE"
    READMODEL_SQL_DB_SCHEMA_PURPOSE_TEMPLATE: "common-read-model-sql.DB_SCHEMA_PURPOSE_TEMPLATE"
    READMODEL_SQL_DB_SCHEMA_TENANT: "common-read-model-sql.DB_SCHEMA_TENANT"

  envFromSecrets:
    READMODEL_SQL_DB_USERNAME: "platform-data-eservice-descriptors-scheduled-archiver-user.username"
    READMODEL_SQL_DB_PASSWORD: "platform-data-eservice-descriptors-scheduled-archiver-user.password"
