apiVersion: v1
kind: ConfigMap
metadata:
  name: common-in-app-notification-db
  namespace: dev
data:
  DB_HOST: "interop-platform-data-dev.cluster-cevisn7oellx.eu-south-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "in_app_notification"
  DB_USE_SSL: "true"
  DB_SCHEMA: "dev_notification"
