apiVersion: v1
kind: ConfigMap
metadata:
  name: common-tenant-kind-history-db
  namespace: dev
data:
  DB_HOST_RW: "PLACEHOLDER" # TODO: replace with actual DB host (RW)
  DB_HOST_RO: "PLACEHOLDER" # TODO: replace with actual DB host (RO)
  DB_PORT: "5432"
  DB_NAME: "PLACEHOLDER" # TODO: replace with actual DB name
  DB_USE_SSL: "true"
  DB_SCHEMA: "dev_tenant_kind_history"
