name: "interop-be-tenant-readmodel-writer"
techStack: "nodejs"

service:
  create: false

serviceAccount:
  roleArn: "arn:aws:iam::565393043798:role/interop-be-tenant-readmodel-writer-vapt-es1"

configmap:
  KAFKA_CLIENT_ID: "{{.Values.namespace}}-pagopa-interop-tenant"
  KAFKA_GROUP_ID: "{{.Values.namespace}}-tenant-readmodel-writer"

deployment:
  replicas: 0
  env:
    PORT: "8088"
    HOST: "0.0.0.0"
    TOPIC_STARTING_OFFSET: "earliest"
  envFromFieldRef:
    AWS_ROLE_SESSION_NAME: "metadata.name"
  envFromConfigmaps:
    TENANT_TOPIC: "common-kafka.TENANT_TOPIC"
    KAFKA_BROKERS: "common-kafka.KAFKA_BROKERS"
    READMODEL_DB_HOST: "common-read-model.READMODEL_DB_HOST"
    READMODEL_DB_NAME: "common-read-model.READMODEL_DB_NAME"
    READMODEL_DB_PORT: "common-read-model.READMODEL_DB_PORT"
    READMODEL_DB_REPLICA_SET: "common-read-model.READMODEL_REPLICA_SET"
    READMODEL_DB_READ_PREFERENCE: "common-read-model.READMODEL_READ_PREFERENCE"
  envFromSecrets:
    READMODEL_DB_USERNAME: "read-model.PROJECTION_USR"
    READMODEL_DB_PASSWORD: "read-model.PROJECTION_PSW"