namespace: prod

service:
  targetPort: http
  portName: http

deployment:
  enableRolloutAnnotations: true
  replicas: 1
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxUnavailable: 0%
      maxSurge: 50%
  image:
    repositoryPrefix: "505630707203.dkr.ecr.eu-south-1.amazonaws.com"
    imagePullPolicy: Always
    tag: $IMAGE_TAG_PLACEHOLDER
    digest: $IMAGE_DIGEST_PLACEHOLDER
  env:
    LOG_LEVEL: "info"
    NODE_ENV: "production"
  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

local:
  interop_be_commons:
    RSA_KEYS_IDENTIFIERS: "9432c16b-7aae-49df-b9c4-ea61b556652b"
    DEV_ENDPOINTS_ENABLED: "false"
    ENABLED_PROJECTIONS: "false"
