name: interop-be-email-digest-dispatcher

serviceAccount:
  roleArn: "arn:aws:iam::{{.Values.local.awsAccountId}}:role/interop-be-email-digest-dispatcher-{{.Values.namespace}}-es1"

configmap:
  KAFKA_GROUP_ID: "{{.Values.namespace}}-email-digest-dispatcher"
  TOPIC_STARTING_OFFSET: "latest"
  PRODUCER_KAFKA_TRANSACTIONAL_ID: "{{.Values.namespace}}-email-digest-dispatcher-transactional-id"

cronjob:
  schedule: "0 7 * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  restartPolicy: OnFailure

  flywayInitContainer:
    create: true
    migrationsConfigmap: "flyway-digest-tracking"
    env:
      FLYWAY_CREATE_SCHEMAS: true
      FLYWAY_PLACEHOLDER_REPLACEMENT: true
      FLYWAY_PLACEHOLDERS_NAMESPACE: "{{.Values.namespace}}"
      FLYWAY_URL: jdbc:postgresql://$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)
      FLYWAY_SCHEMAS: "{{.Values.namespace}}_digest_tracking"
    envFromConfigmaps:
      POSTGRES_HOST: "common-digest-tracking-db.DB_HOST_RW"
      POSTGRES_PORT: "common-digest-tracking-db.DB_PORT"
      POSTGRES_DB: "common-digest-tracking-db.DB_NAME"
    envFromSecrets:
      FLYWAY_USER: "platform-data-flyway-user.username"
      FLYWAY_PASSWORD: "platform-data-flyway-user.password"

  env:
    BFF_URL: "https://selfcare.interop.pagopa.it/1.0/backend-for-frontend"
    DIGEST_FREQUENCY_HOURS: "168"
    #Ministero delle infrastrutture e dei trasporti,Istituto Nazionale Previdenza Sociale - INPS,Ministero del Lavoro e delle Politiche Sociali,Agenzia delle Entrate,Dipartimento della Funzione Pubblica,Ministero dell'Interno,MINISTERO DELL'UNIVERSITA' E DELLA RICERCA,Ministero dell'istruzione e del merito",
    PRIORITY_PRODUCER_IDS: "6c07e769-b418-4210-bc0f-7d56470a06e9,53b40136-65f2-424b-acfb-7fae17e35c60,2e1c950b-26d6-471a-b5ec-bd233d5b1f07,bce8d16d-d26f-4c35-a835-35cca48ff8a5,87ac321d-f13f-49f3-8aa8-2aaae9dc2115,2a9ad360-90ef-4499-ab2c-112b0fbcecc7,27aaf0d7-850b-4aca-92b8-f4df70217448,86a2adeb-bf90-4248-b471-58ba3539f423" 
    
  envFromConfigmaps:
    EMAIL_DISPATCH_TOPIC: "common-kafka.EMAIL_DISPATCH_TOPIC"
    PRODUCER_KAFKA_BROKERS: "common-kafka.KAFKA_BROKERS"
    READMODEL_SQL_DB_HOST: "common-read-model-sql.DB_HOST_RO"
    READMODEL_SQL_DB_PORT: "common-read-model-sql.DB_PORT"
    READMODEL_SQL_DB_NAME: "common-read-model-sql.DB_NAME"
    READMODEL_SQL_DB_USE_SSL: "common-read-model-sql.DB_USE_SSL"
    READMODEL_SQL_DB_SCHEMA_AGREEMENT: "common-read-model-sql.DB_SCHEMA_AGREEMENT"
    READMODEL_SQL_DB_SCHEMA_ATTRIBUTE: "common-read-model-sql.DB_SCHEMA_ATTRIBUTE"
    READMODEL_SQL_DB_SCHEMA_CATALOG: "common-read-model-sql.DB_SCHEMA_CATALOG"
    READMODEL_SQL_DB_SCHEMA_DELEGATION: "common-read-model-sql.DB_SCHEMA_DELEGATION"
    READMODEL_SQL_DB_SCHEMA_ESERVICE_TEMPLATE: "common-read-model-sql.DB_SCHEMA_ESERVICE_TEMPLATE"
    READMODEL_SQL_DB_SCHEMA_NOTIFICATION_CONFIG: "common-read-model-sql.DB_SCHEMA_NOTIFICATION_CONFIG"
    READMODEL_SQL_DB_SCHEMA_PURPOSE: "common-read-model-sql.DB_SCHEMA_PURPOSE"
    READMODEL_SQL_DB_SCHEMA_TENANT: "common-read-model-sql.DB_SCHEMA_TENANT"
    DIGEST_TRACKING_DB_HOST: "common-digest-tracking-db.DB_HOST_RW"
    DIGEST_TRACKING_DB_PORT: "common-digest-tracking-db.DB_PORT"
    DIGEST_TRACKING_DB_NAME: "common-digest-tracking-db.DB_NAME"
    DIGEST_TRACKING_DB_USE_SSL: "common-digest-tracking-db.DB_USE_SSL"
    DIGEST_TRACKING_DB_SCHEMA: "common-digest-tracking-db.DB_SCHEMA"
  envFromSecrets:
    DIGEST_TRACKING_DB_USERNAME: "platform-data-email-digest-dispatcher-user.username"
    DIGEST_TRACKING_DB_PASSWORD: "platform-data-email-digest-dispatcher-user.password"
    READMODEL_SQL_DB_USERNAME: "platform-data-email-digest-dispatcher-user.username"
    READMODEL_SQL_DB_PASSWORD: "platform-data-email-digest-dispatcher-user.password"
  envFromFieldRef:
    AWS_ROLE_SESSION_NAME: "metadata.name"
    PRODUCER_KAFKA_CLIENT_ID: "metadata.name"