name: "interop-be-one-trust-notices"

serviceAccount:
  roleArn: "arn:aws:iam::755649575658:role/interop-be-one-trust-notices-qa-es1"

configmap:
  LANGS: "it"
  CONTENT_STORAGE_BUCKET: "interop-privacy-notices-content-qa-es1"
  HISTORY_STORAGE_BUCKET: "interop-privacy-notices-history-qa-es1"
  PRIVACY_NOTICES_UPDATER_PRIVACY_POLICY_UUID: "0df21ff6-3e8f-4320-af8f-23dea9135d57"
  PRIVACY_NOTICES_UPDATER_TERMS_OF_SERVICE_UUID: "6bf8412a-41a7-41a0-82dc-26286ce61b1a"

cronjob:
  schedule: "0 */3 * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 0
  restartPolicy: OnFailure
  env:
    ENVIRONMENT: "qa"
    TERMS_OF_SERVICE_NOTICE_ID: ""
    PRIVACY_POLICY_NOTICE_ID: ""
    PRIVACY_NOTICES_DYNAMO_TABLE_NAME: "interop-privacy-notices-qa"
  envFromFieldRef:
    NAMESPACE: "metadata.namespace"
  envFromConfigmaps:
    READMODEL_SQL_DB_HOST: "common-read-model-sql.DB_HOST_RO"
    READMODEL_SQL_DB_PORT: "common-read-model-sql.DB_PORT"
    READMODEL_SQL_DB_NAME: "common-read-model-sql.DB_NAME"
    READMODEL_SQL_DB_USE_SSL: "common-read-model-sql.DB_USE_SSL"
    READMODEL_SQL_DB_SCHEMA_AGREEMENT: "common-read-model-sql.DB_SCHEMA_AGREEMENT"
    READMODEL_SQL_DB_SCHEMA_ATTRIBUTE: "common-read-model-sql.DB_SCHEMA_ATTRIBUTE"
    READMODEL_SQL_DB_SCHEMA_CATALOG: "common-read-model-sql.DB_SCHEMA_CATALOG"
    READMODEL_SQL_DB_SCHEMA_CLIENT_JWK_KEY: "common-read-model-sql.DB_SCHEMA_CLIENT_JWK_KEY"
    READMODEL_SQL_DB_SCHEMA_CLIENT: "common-read-model-sql.DB_SCHEMA_CLIENT"
    READMODEL_SQL_DB_SCHEMA_DELEGATION: "common-read-model-sql.DB_SCHEMA_DELEGATION"
    READMODEL_SQL_DB_SCHEMA_ESERVICE_TEMPLATE: "common-read-model-sql.DB_SCHEMA_ESERVICE_TEMPLATE"
    READMODEL_SQL_DB_SCHEMA_PRODUCER_JWK_KEY: "common-read-model-sql.DB_SCHEMA_PRODUCER_JWK_KEY"
    READMODEL_SQL_DB_SCHEMA_PRODUCER_KEYCHAIN: "common-read-model-sql.DB_SCHEMA_PRODUCER_KEYCHAIN"
    READMODEL_SQL_DB_SCHEMA_PURPOSE: "common-read-model-sql.DB_SCHEMA_PURPOSE"
    READMODEL_SQL_DB_SCHEMA_TENANT: "common-read-model-sql.DB_SCHEMA_TENANT"
    FEATURE_FLAG_SQL: "common-feature-flags.FEATURE_FLAG_SQL"
  envFromSecrets:
    ONETRUST_CLIENT_ID: "onetrust.ONETRUST_CLIENT_ID"
    ONETRUST_CLIENT_SECRET: "onetrust.ONETRUST_CLIENT_SECRET"
    READMODEL_SQL_DB_USERNAME: "platform-data-readonly-user.username"
    READMODEL_SQL_DB_PASSWORD: "platform-data-readonly-user.password"
