name: "interop-be-pn-consumers"

serviceAccount:
  roleArn: "arn:aws:iam::697818730278:role/interop-be-pn-consumers-prod-es1"

configmap:
  PN_ESERVICE_ID: "cfc8a94d-001a-4ab6-bb5c-2509b2a68af1"
  COMUNI_E_LORO_CONSORZI_E_ASSOCIAZIONI_ATTRIBUTE_ID: "14d266fd-f99d-49d8-9113-ad054226e0bf"
  REPORT_SENDER_MAIL: "noreply@reports.interop.pagopa.it"
  REPORT_SENDER_LABEL: "noreply"

cronjob:
  schedule: "0 7 */2 * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 0
  restartPolicy: OnFailure
  automountServiceAccountToken: false
  envFromFieldRef:
    NAMESPACE: "metadata.namespace"
  envFromConfigmaps:
    READMODEL_DB_HOST: "common-read-model.READMODEL_DB_HOST"
    READMODEL_DB_PORT: "common-read-model.READMODEL_DB_PORT"
    READMODEL_DB_NAME: "common-read-model.READMODEL_DB_NAME"
    READMODEL_SQL_DB_HOST: "common-read-model-sql.DB_HOST_RO"
    READMODEL_SQL_DB_PORT: "common-read-model-sql.DB_PORT"
    READMODEL_SQL_DB_NAME: "common-read-model-sql.DB_NAME"
    READMODEL_SQL_DB_USE_SSL: "common-read-model-sql.DB_USE_SSL"
    READMODEL_SQL_DB_SCHEMA_AGREEMENT: "common-read-model-sql.DB_SCHEMA_AGREEMENT"
    READMODEL_SQL_DB_SCHEMA_ATTRIBUTE: "common-read-model-sql.DB_SCHEMA_ATTRIBUTE"
    READMODEL_SQL_DB_SCHEMA_CATALOG: "common-read-model-sql.DB_SCHEMA_CATALOG"
    READMODEL_SQL_DB_SCHEMA_CLIENT_JWK_KEY: "common-read-model-sql.DB_SCHEMA_CLIENT_JWK_KEY"
    READMODEL_SQL_DB_SCHEMA_CLIENT: "common-read-model-sql.DB_SCHEMA_CLIENT"
    READMODEL_SQL_DB_SCHEMA_DELEGATION: "common-read-model-sql.DB_SCHEMA_DELEGATION"
    READMODEL_SQL_DB_SCHEMA_ESERVICE_TEMPLATE: "common-read-model-sql.DB_SCHEMA_ESERVICE_TEMPLATE"
    READMODEL_SQL_DB_SCHEMA_PRODUCER_JWK_KEY: "common-read-model-sql.DB_SCHEMA_PRODUCER_JWK_KEY"
    READMODEL_SQL_DB_SCHEMA_PRODUCER_KEYCHAIN: "common-read-model-sql.DB_SCHEMA_PRODUCER_KEYCHAIN"
    READMODEL_SQL_DB_SCHEMA_PURPOSE: "common-read-model-sql.DB_SCHEMA_PURPOSE"
    READMODEL_SQL_DB_SCHEMA_TENANT: "common-read-model-sql.DB_SCHEMA_TENANT"
    FEATURE_FLAG_SQL: "common-feature-flags.FEATURE_FLAG_SQL"
  envFromSecrets:
    READMODEL_DB_USERNAME: "read-model.READONLY_USR"
    READMODEL_DB_PASSWORD: "read-model.READONLY_PSW"
    MAIL_RECIPIENTS: "pn-consumers.MAIL_RECIPIENTS"
    READMODEL_SQL_DB_USERNAME: "platform-data-pn-consumers-user.username"
    READMODEL_SQL_DB_PASSWORD: "platform-data-pn-consumers-user.password"
