apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: dev-experimental-argocd-interop-apps
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: eso-sa
