apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-sa
  namespace: dev-experimental-argocd-interop-apps
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::505630707203:role/interop-experimental-eso-dev-broke
