apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: experimental-eso-markertest
  namespace: {{ .Values.namespace }}
spec:
  refreshPolicy: OnChange
  refreshInterval: "0"
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: experimental-eso-markertest
    creationPolicy: Merge
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        {{- if and .Values.locals .Values.locals.externalSecrets .Values.locals.externalSecrets.remoteSecrets }}
        annotations:
          {{- $pairs := list -}}
          {{- range .Values.locals.externalSecrets.remoteSecrets }}
          {{- $pairs = append $pairs (printf "%s=%s" .id .version) -}}
          {{- end }}
          externalsecret/secret-applied-hash: {{ join "|" (sortAlpha $pairs) | sha256sum | quote }}
        {{- end }}
  data:
  - secretKey: FOO
    remoteRef:
      key: experimental-eso/foo/bar
      property: foo
  - secretKey: IKI
    remoteRef:
      key: experimental-eso/foo/bar
      property: iki
  - secretKey: DATABASE
    remoteRef:
      key: rds/interop-platform-data-dev/users/dev_email_digest_dispatcher_user
      property: database
  - secretKey: USERNAME
    remoteRef:
      key: rds/interop-platform-data-dev/users/dev_email_digest_dispatcher_user
      property: username
