apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: experimental-eso-markertest
  namespace: dev-experimental-argocd-interop-apps
spec:
  refreshPolicy: OnChange
  refreshInterval: "0"
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: experimental-eso-markertest
    creationPolicy: Merge
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        annotations:
          externalsecret/secret-applied-hash: "v1"
  data:
  - secretKey: FOO
    remoteRef:
      key: experimental-eso/foo/bar
      property: foo
      #version: d7c45042-5f08-4aab-b0b4-f2755277d49f
  - secretKey: IKI
    remoteRef:
      key: experimental-eso/foo/bar
      property: iki
      #version: d7c45042-5f08-4aab-b0b4-f2755277d49f
  - secretKey: DATABASE
    remoteRef:
      key: rds/interop-platform-data-dev/users/dev_email_digest_dispatcher_user
      property: database
  - secretKey: USERNAME
    remoteRef:
      key: rds/interop-platform-data-dev/users/dev_email_digest_dispatcher_user
      property: username
