apiVersion: v1
kind: Secret
metadata:
  name: experimental-eso-markertest
  namespace: {{ .Values.namespace }}
  annotations:
    externalsecret/secret-contract-hash: {{ .Values.local.externalSecrets.markerValue | quote }}
type: Opaque
stringData: {}