apiVersion: v1
kind: Secret
metadata:
  name: experimental-eso-markertest
  namespace: {{ .Values.namespace }}
  annotations:
    {{- if and .Values.locals .Values.locals.externalSecrets .Values.locals.externalSecrets.remoteSecrets }}
    {{- $pairs := list -}}
    {{- range .Values.locals.externalSecrets.remoteSecrets }}
    {{- $pairs = append $pairs (printf "%s=%s" .id .version) -}}
    {{- end -}}
    externalsecret/secret-contract-hash: {{ join "|" (sortAlpha $pairs) | sha256sum | quote }}
    {{- end -}}
type: Opaque
stringData: {}