apiVersion: v1
kind: Secret
metadata:
  name: experimental-eso-markertest
  namespace: dev-experimental-argocd-interop-apps
  labels:
    eso-managed: "true"
  annotations:
    externalsecret/secret-contract-hash: "v1"
type: Opaque
stringData: {}