namespace: "vapt"

cronjob:
  suspend: true
  image:
    repositoryPrefix: "505630707203.dkr.ecr.eu-south-1.amazonaws.com"
    imagePullPolicy: Always
    tag: $IMAGE_TAG_PLACEHOLDER
    digest: $IMAGE_DIGEST_PLACEHOLDER
  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  env:
    LOG_LEVEL: "info"
    NODE_ENV: "production"

local:
  interop_be_commons:
    RSA_KEYS_IDENTIFIERS: "65ce3bd3-88ed-40c1-9787-0a55e7f35332"
