namespace: vapt

service:
  containerPort: 8088
  targetPort: http
  portName: http

deployment:
  replicas: 1
  image:
    repositoryPrefix: "505630707203.dkr.ecr.eu-south-1.amazonaws.com"
    imagePullPolicy: Always
    tag: $IMAGE_TAG_PLACEHOLDER
    digest: $IMAGE_DIGEST_PLACEHOLDER
  flyway:
    commonsDbConfigmapName: "interop-be-db-commons"
  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
