namespace: "dev"
techStack: "nodejs"

service:
  containerPort: 8088
  targetPort: http
  portName: "http"

deployment:
  flywayInitContainer:
    migrationsConfigmap: "event-store-migrations"
  replicas: 1
  image:
    repositoryPrefix: "505630707203.dkr.ecr.eu-south-1.amazonaws.com"
    imagePullPolicy: Always
    tag: $IMAGE_TAG_PLACEHOLDER
    digest: $IMAGE_DIGEST_PLACEHOLDER
  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
  env:
    LOG_LEVEL: "info"


locals:
  db:
    POSTGRES_HOST: "interop-platform-data-dev.cluster-cevisn7oellx.eu-south-1.rds.amazonaws.com"
    POSTGRES_PORT: "5432"
    POSTGRES_DB: "persistence_management"