deployment:
  flywayInitContainer:
    create: true
    migrationsConfigmap: "event-store-migrations"
    env:
      FLYWAY_CREATE_SCHEMAS: "true"
      FLYWAY_PLACEHOLDER_REPLACEMENT: "true"
      FLYWAY_URL: jdbc:postgresql://$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)
    envFromConfigmaps:
      FLYWAY_SCHEMAS: "{{.Values.name}}.EVENTSTORE_DB_SCHEMA"
      FLYWAY_PLACEHOLDERS_APPLICATIONSCHEMA: "{{.Values.name}}.EVENTSTORE_DB_SCHEMA"
      POSTGRES_DB: "common-event-store.EVENTSTORE_DB_NAME"
      POSTGRES_HOST: "common-event-store.EVENTSTORE_DB_HOST"
      POSTGRES_PORT: "common-event-store.EVENTSTORE_DB_PORT"
    envFromSecrets:
      FLYWAY_USER: "event-store.POSTGRES_USR"
      FLYWAY_PASSWORD: "event-store.POSTGRES_PSW"