name: "interop-be-risk-analysis-processing"

serviceAccount:
  roleArn: "arn:aws:iam::{{.Values.local.awsAccountId}}:role/interop-be-risk-analysis-processing-{{.Values.namespace}}-es1"

configmap:
  INTERNAL_JWT_KID: "{{.Values.local.interop_be_commons.RSA_KEYS_IDENTIFIERS}}"
  INTERNAL_JWT_SUBJECT: "interop-m2m"
  INTERNAL_JWT_ISSUER: "interop.pagopa.it"
  INTERNAL_JWT_AUDIENCE: "interop.pagopa.it/internal"
  INTERNAL_JWT_SECONDS_DURATION: "1800"
  FIX_LIST_TENANT_KIND_RISK_ANALYSIS_ESERVICE_TEMPLATES: ""

cronjob:
  schedule: "0 0 * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 0
  restartPolicy: OnFailure
  automountServiceAccountToken: false
  suspend: true
  envFromConfigmaps:
    CATALOG_PROCESS_URL: "common-services-urls.CATALOG_PROCESS_URL"
    PURPOSE_PROCESS_URL: "common-services-urls.PURPOSE_PROCESS_URL"
    ESERVICE_TEMPLATE_PROCESS_URL: "common-services-urls.ESERVICE_TEMPLATE_PROCESS_URL"
    READMODEL_SQL_DB_HOST: "common-read-model-sql.DB_HOST_RO"
    READMODEL_SQL_DB_PORT: "common-read-model-sql.DB_PORT"
    READMODEL_SQL_DB_NAME: "common-read-model-sql.DB_NAME"
    READMODEL_SQL_DB_USE_SSL: "common-read-model-sql.DB_USE_SSL"
    READMODEL_SQL_DB_SCHEMA_CATALOG: "common-read-model-sql.DB_SCHEMA_CATALOG"
    READMODEL_SQL_DB_SCHEMA_PURPOSE: "common-read-model-sql.DB_SCHEMA_PURPOSE"
    READMODEL_SQL_DB_SCHEMA_ESERVICE_TEMPLATE: "common-read-model-sql.DB_SCHEMA_ESERVICE_TEMPLATE"
  envFromSecrets:
    READMODEL_SQL_DB_USERNAME: "platform-data-risk-analysis-processing-user.username"
    READMODEL_SQL_DB_PASSWORD: "platform-data-risk-analysis-processing-user.password"
