name: "interop-be-notification-email-sender"
techStack: "nodejs"

serviceAccount:
  roleArn: "arn:aws:iam::755649575658:role/interop-be-notification-email-sender-qa-es1"

service:
  create: false

configmap:
  INTEROP_FE_BASE_URL: "selfcare.{{.Values.namespace}}.interop.pagopa.it"
  AWS_SES_ENDPOINT: "http://ses-mock.{{.Values.namespace}}.svc.cluster.local:8005"
  SENDER_MAIL: "noreply@notifiche.{{.Values.namespace}}.interop.pagopa.it"
  SENDER_LABEL: "noreply-{{.Values.namespace}}"
  KAFKA_GROUP_ID: "{{.Values.namespace}}-notification-email-sender"
  KAFKA_CLIENT_ID: "{{.Values.namespace}}-pagopa-interop-notification-email-sender"
  REDIS_NOTIFICATION_EMAIL_SENDER_TTL_SECONDS: "2592000"
  SMTP_ADDRESS: "smtp-mock.{{.Values.namespace}}.svc.cluster.local"
  SMTP_PORT: "5025"
  SMTP_SECURE: "false"

deployment:
  env:
    TOPIC_STARTING_OFFSET: "latest"
  envFromFieldRef:
    NAMESPACE: "metadata.namespace"
    AWS_ROLE_SESSION_NAME: "metadata.name"
  envFromConfigmaps:
    AGREEMENT_TOPIC: "common-kafka.AGREEMENT_TOPIC"
    CATALOG_TOPIC: "common-kafka.CATALOG_TOPIC"
    PURPOSE_TOPIC: "common-kafka.PURPOSE_TOPIC"
    KAFKA_BROKERS: "common-kafka.KAFKA_BROKERS"
    READMODEL_DB_HOST: "common-read-model.READMODEL_DB_HOST"
    READMODEL_DB_NAME: "common-read-model.READMODEL_DB_NAME"
    READMODEL_DB_PORT: "common-read-model.READMODEL_DB_PORT"
    READMODEL_SQL_DB_HOST: "common-read-model-sql.DB_HOST_RO"
    READMODEL_SQL_DB_PORT: "common-read-model-sql.DB_PORT"
    READMODEL_SQL_DB_NAME: "common-read-model-sql.DB_NAME"
    READMODEL_SQL_DB_USE_SSL: "common-read-model-sql.DB_USE_SSL"
    READMODEL_SQL_DB_SCHEMA_AGREEMENT: "common-read-model-sql.DB_SCHEMA_AGREEMENT"
    READMODEL_SQL_DB_SCHEMA_ATTRIBUTE: "common-read-model-sql.DB_SCHEMA_ATTRIBUTE"
    READMODEL_SQL_DB_SCHEMA_CATALOG: "common-read-model-sql.DB_SCHEMA_CATALOG"
    READMODEL_SQL_DB_SCHEMA_CLIENT_JWK_KEY: "common-read-model-sql.DB_SCHEMA_CLIENT_JWK_KEY"
    READMODEL_SQL_DB_SCHEMA_CLIENT: "common-read-model-sql.DB_SCHEMA_CLIENT"
    READMODEL_SQL_DB_SCHEMA_DELEGATION: "common-read-model-sql.DB_SCHEMA_DELEGATION"
    READMODEL_SQL_DB_SCHEMA_ESERVICE_TEMPLATE: "common-read-model-sql.DB_SCHEMA_ESERVICE_TEMPLATE"
    READMODEL_SQL_DB_SCHEMA_NOTIFICATION_CONFIG: "common-read-model-sql.DB_SCHEMA_NOTIFICATION_CONFIG"
    READMODEL_SQL_DB_SCHEMA_PRODUCER_JWK_KEY: "common-read-model-sql.DB_SCHEMA_PRODUCER_JWK_KEY"
    READMODEL_SQL_DB_SCHEMA_PRODUCER_KEYCHAIN: "common-read-model-sql.DB_SCHEMA_PRODUCER_KEYCHAIN"
    READMODEL_SQL_DB_SCHEMA_PURPOSE: "common-read-model-sql.DB_SCHEMA_PURPOSE"
    READMODEL_SQL_DB_SCHEMA_TENANT: "common-read-model-sql.DB_SCHEMA_TENANT"
    FEATURE_FLAG_SQL: "common-feature-flags.FEATURE_FLAG_SQL"
    REDIS_NOTIFICATION_EMAIL_SENDER_HOST: "common-redis.REDIS_HOST"
    REDIS_NOTIFICATION_EMAIL_SENDER_PORT: "common-redis.REDIS_PORT"
  envFromSecrets:
    READMODEL_DB_USERNAME: "read-model.READONLY_USR"
    READMODEL_DB_PASSWORD: "read-model.READONLY_PSW"
    SMTP_USERNAME: "smtp-notifications.SMTP_USER"
    SMTP_PASSWORD: "smtp-notifications.SMTP_PASSWORD"
    READMODEL_SQL_DB_USERNAME: "platform-data-notification-email-sender-user.username"
    READMODEL_SQL_DB_PASSWORD: "platform-data-notification-email-sender-user.password"
