apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: interop-microservices
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                - git:
                    repoURL: git@github.com:pagopa/interop-core-deployment.git
                    revision: HEAD
                    files:
                      - path: commons/dev/images.yaml
                - git:
                    repoURL: git@github.com:pagopa/interop-core-deployment.git
                    revision: HEAD
                    pathParamPrefix: ms
                    directories:
                      - path: microservices/*/dev
  template:
    metadata:
      name: "{{index .ms.path.segments 2}}"
      namespace: argocd
    spec:
      project: "interop-dev"
      sources:
        - repoURL: git@github.com:pagopa/interop-core-deployment.git
          path: "."
          targetRevision: HEAD
          ref: values
        - repoURL: https://pagopa.github.io/interop-eks-cronjob-chart
          chart: interop-eks-cronjob-chart
          targetRevision: 1.46.0
          helm:
            releaseName: "{{index .ms.path.segments 2}}"
            valueFiles:
              #- $values/commons/dev/values-commons.yaml
              - $values/commons/dev/values-microservice.yaml
              - $values/microservices/{{index .ms.path.segments 2}}/dev/values.yaml
              - $values/commons/dev/images.yaml
            values: |
              {{- $images := .images | default dict -}}
              {{- $msmap := (index $images "microservices") | default dict -}}
              {{- $ms := (index $msmap (index .ms.path.segments 2)) | default dict -}}
              deployment:
                image:
                  tag: {{ get $ms "tag" | default "" }}
                  digest: {{ get $ms "digest" | default "" }}
      destination:
        server: https://kubernetes.default.svc
        namespace: "dev"
      ignoreDifferences:
        - group: ""
          kind: Secret
          jsonPointers:
            - /data
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=false
          - RespectIgnoreDifferences=true
