apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: interop-app-root
  namespace: dev
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  sources:
  - repoURL: https://github.com/pagopa/interop-core-deployment.git
    targetRevision: feature/argocd
    path: argocd/dev
    directory:
      include: 'common-cm.yaml'
  - repoURL: https://github.com/pagopa/interop-core-deployment.git
    targetRevision: feature/argocd
    path: argocd/dev
    directory:
      include: 'microservices-appset.yaml'
  - repoURL: https://github.com/pagopa/interop-core-deployment.git
    targetRevision: feature/argocd
    path: argocd/dev
    directory:
      include: 'cronjobs-appset.yaml'
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
