name: Generic PR Validation

on: 
  workflow_call:
    inputs:
      environment:
        description: 'Environment to run diff against'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  common_values_validation:
    secrets: inherit
    uses: pagopa/interop-infra-commons/.github/workflows/common-deployment-values-validation.yaml@feature/pin-10584-validation-pipeline
    with:
      environment: ${{ inputs.environment }}
      infra_commons_tag: "feature/pin-10584-validation-pipeline"
      enable_kube_linter: false
      enable_argocd_validation: true
      enable_argocd_schema_validation: true
      repo_structure_validation_warning_only: false   
