name: PR Validation - Main Starter

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  id-token: write
  contents: read
jobs:
  validation:
    name: "Validation – ${{ matrix.environment }}"
    strategy:
      fail-fast: false
      matrix:
        environment: [dev, qa, vapt]
    uses: pagopa/interop-infra-commons/actions/deployment-values-validation.yaml@main
    with:
      environment: ${{ matrix.environment }}